from database import Base
from sqlalchemy import Date, String, Boolean, Integer, Float
from sqlalchemy.orm import mapped_column


class Pitch(Base):
    __tablename__ = "pitches"
    guid = mapped_column(String, primary_key=True)
    game_date = mapped_column(Date)
    game_bam_id = mapped_column(Integer)
    venue_bam_id = mapped_column(Integer)
    venue = mapped_column(String)
    league = mapped_column(String)
    away_team = mapped_column(String)
    home_team = mapped_column(String)
    pitch_seq = mapped_column(Integer)
    is_pitch = mapped_column(Boolean)
    is_pickoff = mapped_column(Boolean)
    is_stepoff = mapped_column(Boolean)
    is_balk = mapped_column(Boolean)
    terminating = mapped_column(Boolean)
    pitch_code = mapped_column(String)
    pitch_result = mapped_column(String)
    event_type = mapped_column(String, nullable=True)
    description = mapped_column(String, nullable=True)
    inning = mapped_column(Integer)
    bottom = mapped_column(Boolean)
    at_bat_number = mapped_column(Integer)
    pre_balls = mapped_column(Integer)
    pre_strikes = mapped_column(Integer)
    pre_outs = mapped_column(Integer)
    pre_basecode = mapped_column(Integer)
    pre_vscore = mapped_column(Integer)
    pre_hscore = mapped_column(Integer)
    post_balls = mapped_column(Integer)
    post_strikes = mapped_column(Integer)
    post_outs = mapped_column(Integer)
    post_basecode = mapped_column(Integer)
    post_vscore = mapped_column(Integer)
    post_hscore = mapped_column(Integer)
    pitcher_team = mapped_column(String)
    pitcher_bam_id = mapped_column(Integer)
    pitcher_name_first = mapped_column(String)
    pitcher_name_last = mapped_column(String)
    pitcher_set = mapped_column(String, nullable=True)
    pitcher_side = mapped_column(String)
    pitcher_type = mapped_column(String)
    batter_team_bam_id = mapped_column(Integer)
    batter_team = mapped_column(String)
    batter_bam_id = mapped_column(Integer)
    batter_name_first = mapped_column(String)
    batter_name_last = mapped_column(String)
    batter_side = mapped_column(String)
    batter_position = mapped_column(Integer)
    catcher_bam_id = mapped_column(Integer)
    fielder_position = mapped_column(Integer, nullable=True)
    fielder_bam_id = mapped_column(Integer, nullable=True)
    pitch_type = mapped_column(String, nullable=True)
    rel_speed = mapped_column(Float, nullable=True)
    plate_time = mapped_column(Float, nullable=True)
    hit_trajectory = mapped_column(String, nullable=True)
    hit_exit_speed = mapped_column(Float, nullable=True)
    hit_distance = mapped_column(Float, nullable=True)
    hit_swing_speed = mapped_column(Float, nullable=True)
    bat_speed = mapped_column(Float, nullable=True)
    wild_pitch = mapped_column(Integer)
    passed_ball = mapped_column(Integer)
    in_zone = mapped_column(Boolean, nullable=True)
    swing = mapped_column(Boolean)
    contact = mapped_column(Boolean)
    in_play = mapped_column(Boolean)
    ball = mapped_column(Boolean)
    called_strike = mapped_column(Boolean)
    swinging_strike = mapped_column(Boolean)
    chase = mapped_column(Boolean)
    foul = mapped_column(Boolean)
    bunt_attempt = mapped_column(Boolean)
